services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
    image: activitypods/backend:${TAG}

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
    image: activitypods/frontend:${TAG}
    env_file:
      - ./frontend/.env

  arena:
    build:
      context: .
      dockerfile: ./docker/arena.dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
    image: activitypods/arena:${TAG}
    environment:
      REDIS_HOST: 'redis'
